services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: phonebook
      POSTGRES_PASSWORD: phonebook
      POSTGRES_DB: phonebook
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    depends_on:
      - db
    env_file:
      - ./backend/.env 
    ports:
      - "5001:5000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
volumes:
  db_data: